steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/keralty-agent-backend:$COMMIT_SHA', './backend']
  
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/keralty-agent-frontend:$COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://keralty-agent-backend-569920970367.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_ADMIN_ENABLED=true'
      - './frontend'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/keralty-agent-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/keralty-agent-frontend:$COMMIT_SHA']

  # Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'keralty-agent-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/keralty-agent-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'keralty-agent-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/keralty-agent-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/keralty-agent-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/keralty-agent-frontend:$COMMIT_SHA'
